### ISSUE TITLE
TrackCallBack 接口的使用

### ISSUE THREAD

**Issue by Sanster** [zeusees/HyperLandmark#11]
感谢开源这么好的项目！有个问题想请教一下，`TrackCallBack`  如何使用？我在 demo 里加了 Log 打印，并没有输出。

![image](https://user-images.githubusercontent.com/3998421/45014703-0f948a80-b052-11e8-96a7-599c22213c4e.png)

**Comment by lsy17096535** [comment]
稍等我们完善接口跟文档，不好意思回复慢了。

**Comment by memorise** [comment]
这个TrackCallBack依然没有被调用到
