### ISSUE TITLE
Android端模型算法

### ISSUE THREAD

**Issue by patrickwf** [zeusees/HyperLandmark#16]
可以简单说一下Android端模型的思路吗？
谢谢~

**Comment by lsy17096535** [comment]
The network is a basic regression network. we design the structure balance proformance and speed.
You can reference some other efficient net such as sufflenet and mobilenet.

**Comment by jlcai5** [comment]
你用的是开源的数据集吗@lsy17096535  安卓侧脸关键点定位很不错，有没有做过c++或者python的

**Comment by lsy17096535** [comment]
@jlcai5  目前只提供android SDK，后期会考虑开源底层代码。

**Comment by LCLL** [comment]
在安卓机器上帧率很稳定，请问ncnn部署的时候使用单线程还是多线程跑的？然后是每一帧都做alignment吗？~谢谢
