### ISSUE TITLE
Use of library on Windows

### ISSUE THREAD

**Issue by DenchiSoft** [zeusees/HyperLandmark#17]
Do you have plans to bring the Android implementation to Windows? It would be really cool to have a .dll or even the code, if it is possible.

Amazing work, by the way! The landmark tracking on the 106 point version is very nice and stable.

**Comment by szad670401** [comment]
I will release a windows library recently.

**Comment by DenchiSoft** [comment]
Awesome, thank you so much. Looking forward to that!

**Comment by DenchiSoft** [comment]
Sorry for reopening, but do you maybe have an approximate date for the windows release?

**Comment by DenchiSoft** [comment]
Do you have any update on this? Or have you stopped development on the Windows version?

Thanks!
