### ISSUE TITLE
Pose detection on android

### ISSUE THREAD

**Issue by HebaMohamed** [zeusees/HyperLandmark#18]
Hello Team,
Thanks a lot for the great work, but how to detect pose on android ?
I really need your help on that part

Thanks in advance

**Comment by lsy17096535** [comment]
Thanks for your interast. We will provide this function later.

**Comment by lsy17096535** [comment]
you can refer  https://github.com/chengzhengxin/sdm or https://github.com/guoqiangqi/PFLD
