### ISSUE TITLE
android上，后置摄像头无法识别

### ISSUE THREAD

**Issue by mghxz252** [zeusees/HyperLandmark#20]
怎么改才可以让手机 前后摄像头都能识别人脸

**Comment by lsy17096535** [comment]
自己做一下镜面翻转

**Comment by mghxz252** [comment]
是对摄像头的数据进行镜面翻转么？

**Comment by lsy17096535** [comment]
是的

**Comment by mghxz252** [comment]
你好，我早后摄像头的情况下，对数据进行了水平镜面翻转，但是还是不能识别，，

**Comment by dxl520** [comment]
>           你好，我早后摄像头的情况下，对数据进行了水平镜面翻转，但是还是不能识别，，
你好，请问你解决后置摄像头不能识别的问题了吗？
