### ISSUE TITLE
请问怎么网络结构可以开源吗？

### ISSUE THREAD

**Issue by BenJaminKen** [zeusees/HyperLandmark#25]

**Comment by xueyedamo** [comment]
运行库都内置了bug存在，你还指望开源网络，和他们商务去谈吧

**Comment by lsy17096535** [comment]
能够把错误日志发一下，我们完善一下。

**Comment by xueyedamo** [comment]
01-08 10:17:54.739 27404-27418/com.sample.multitrack106 E/dalvikvm: Failed adding to JNI pinned array ref table (1024 entries)
01-08 10:17:54.739 27404-27418/com.sample.multitrack106 E/dalvikvm: VM aborting
01-08 10:17:54.739 27404-27418/com.sample.multitrack106 A/libc: Fatal signal 6 (SIGABRT) at 0x00006b0c (code=-6), thread 27418 (DrawFacePointsT)

**Comment by xueyedamo** [comment]
@lsy17096535

**Comment by lsy17096535** [comment]
@xueyedamo 非常感谢，我们尽快修改。
