### ISSUE TITLE
android 可以提供x86的 so文件吗

### ISSUE THREAD

**Issue by 153437803** [zeusees/HyperLandmark#27]

**Comment by lsy17096535** [comment]
ok

**Comment by choiip** [comment]
It's a nice project. Any plan on releasing the arm64-v8a version of so file?

**Comment by nhancv** [comment]
> It's a nice project. Any plan on releasing the arm64-v8a version of so file?
Requesting also be here: 
https://github.com/zeusees/HyperLandmark/issues/51
