### ISSUE TITLE
运行一段时间准时挂掉-jni库内置bug

### ISSUE THREAD

**Issue by xueyedamo** [zeusees/HyperLandmark#32]
请问该代码及贵公司提供的demo app运行一段时间准时挂掉，是不是内存故意没有释放，还是偶然的bug存在？不是说好的开源吗，这让怎么用，也没有训练过程提供，这波广告做的好。

**Comment by BenJaminKen** [comment]
请问运行多久？

**Comment by xueyedamo** [comment]
运行几分钟后必挂，具体时间依赖手机内存
01-08 10:17:54.739 27404-27418/com.sample.multitrack106 E/dalvikvm: Failed adding to JNI pinned array ref table (1024 entries)
01-08 10:17:54.739 27404-27418/com.sample.multitrack106 E/dalvikvm: VM aborting
01-08 10:17:54.739 27404-27418/com.sample.multitrack106 A/libc: Fatal signal 6 (SIGABRT) at 0x00006b0c (code=-6), thread 27418 (DrawFacePointsT)

**Comment by lsy17096535** [comment]
@xueyedamo  我们尽快修改。

**Comment by szad670401** [comment]
不是jni的问题。 我这边另外一个基于opengl es的demo是work正常的。

**Comment by szad670401** [comment]
已修复
