### ISSUE TITLE
请问下，106点的数据是怎末标注的呀

### ISSUE THREAD

**Issue by oftenliu** [zeusees/HyperLandmark#33]

**Comment by ChapterFive-Hero** [comment]
大神，请教下你的运行环境是什么样的呀？我用vs2013跑程序的时候，总是提示我LNK1104: 无法打开文件“opencv_calib3d341d.lib”，我的opencv是3.4.0版本，请指教下

**Comment by lsy17096535** [comment]
@ChapterFive-Hero 你用的3.4.0，就要在链接库->附加项里面，将opencv 3.4.1的lib替换成3.4.0的再去编译。

**Comment by ChapterFive-Hero** [comment]
感谢回答。请问：windows版本的未发布106关键点的模型吗？我忘记说我是在windows上运行的？

**Comment by lsy17096535** [comment]
win版近期会放出来测试，但是不是sdk。

**Comment by ChapterFive-Hero** [comment]
@lsy17096535  感谢回复，68点测试程序我已经跑通了，我原先以为windows发布的也是106点的，再次感谢分享，多谢
