### ISSUE TITLE
是否使用手机上的GPU?

### ISSUE THREAD

**Issue by junedgar** [zeusees/HyperLandmark#36]
你好，感谢你的分享。
我想请教点问题：
1、请问这个face detect 和 face alignment两个模型处理，中间是否使用了手机上的GPU？
2、如果没有使用手机上GPU，mtcnn的参数配置大概是什么样的？比如最小检测人脸多大？
3、face alignment 的模型使用的是博客上的squeezenetv2做backbone吗？
4、人脸检测有没有加跟踪的tricks?

添麻烦了

**Comment by szad670401** [comment]
用手机上GPU并不划算。在现实场景中，某些低端移动端GPU还要用于贴纸动画，场景渲染，可能会导致性能不稳定。
