### ISSUE TITLE
so用在自己的项目上

### ISSUE THREAD

**Issue by zhanglaplace** [zeusees/HyperLandmark#38]
你好，我把.so 和 FaceTracking和Face文件拷贝到自己的项目中，在初始化跟踪模型时，报错，看错误信息是构造函数的createSession函数找不到，这个不是封装在.so中了吗。
![image](https://user-images.githubusercontent.com/12178974/53554818-9480dc80-3b7b-11e9-9dcd-263fee875786.png)

No implementation found for long com.baidu.duerface.FaceTracking.createSession(java.lang.String)

**Comment by lsy17096535** [comment]
你尝试采用跟我们一样的包名看可以吗

**Comment by chongbo2013** [comment]
你好，pitch，yaw，roll 这旋转角度，怎么在视频预览的时候拿到

**Comment by lsy17096535** [comment]
@chongbo2013  根据关键点，进行拟合计算。

**Comment by chongbo2013** [comment]
你demo里有吗

**Comment by chongbo2013** [comment]
你好，能放出android 源码吗

**Comment by qiaowei1214** [comment]
so包里的jni跟java是需要跟包名对应的，所有Face和FaceTracking的 包名必须跟原始的一致，不能用自己工程的。同时也希望作者能够开源native的部分，供大家交流学习，感谢！
