### ISSUE TITLE
关于论文

### ISSUE THREAD

**Issue by patrickwf** [zeusees/HyperLandmark#39]
请问，《PFLD:A Practical Facial Landmark Detector》是你们的论文吗？

**Comment by luckynote** [comment]
展示的视频和demo的样式，以及android源码的文件结构的十分相似，感觉就是这个工程的文章。

**Comment by guoguoguilai** [comment]
我也觉得很像，连模型大小也一模一样

**Comment by guoguoguilai** [comment]
似乎是论文的第一作者，看昵称看出来的。。。厉害了
