### ISSUE TITLE
What‘s the training data?

### ISSUE THREAD

**Issue by Jack-CV** [zeusees/HyperLandmark#41]
Hi, it's cool! I wonder what's the training data you used to train the 106 points model?

**Comment by lsy17096535** [comment]
data labeled by ourself

**Comment by XhqGlorry11** [comment]
@lsy17096535 你好,感谢你们提供高质量的landmark detector,非常棒的结果.最近也看了你们写的论文<PFLD: A Practical Facial Landmark Detector>.论文中提供了一个链接可以下载一个apk,请问:
1.注意到论文中的apk检测结果也是106个点,那个apk中的模型和这里开源的apk中的是相同的吗?
2.论文中的数据和测试结果是在什么数据集上训练得到的?
谢谢.

**Comment by lsy17096535** [comment]
那一版跟这个repo中的模型一样，但是采用了不同的跟踪算法，平滑算法，效果有一些差异。

**Comment by XhqGlorry11** [comment]
@lsy17096535 谢谢.注意到论文那一版的demo中也是显示的106个点.,再请问论文那一版的模型是使用这个repo中的数据集训练的还是使用300w/aflw的数据训练的?

**Comment by XhqGlorry11** [comment]
再多问一句,论文中提交的各项数据指标,是在什么数据集上训练得到的?

**Comment by lsy17096535** [comment]
模型是在300W加上我们增强之后的数据训练的

**Comment by XhqGlorry11** [comment]
@lsy17096535 这.....这样发论文不太好吧,

**Comment by XhqGlorry11** [comment]
@lsy17096535 谢谢,你指的增强是指在300w本身数据通过crop一类的增强,还是说加了新的数据的增强?

**Comment by lsy17096535** [comment]
请看原文

**Comment by XhqGlorry11** [comment]
@lsy17096535 谢谢.注意到原文中提及对于aflw数据集没有做增强,对于300w做了旋转和随机遮挡,我理解这些增强不会改变数据关键点的数量(68个).为什么在论文的demo中检测结果出现了100多个点的检测结果呢?是用了其他的更多关键点的数据吗?

**Comment by lsy17096535** [comment]
106点主要是用来与商业化landmark比较，采用了106点的数据。
