### ISSUE TITLE
关于Android端Demo的图片识别

### ISSUE THREAD

**Issue by Siwroae** [zeusees/HyperLandmark#46]
昨天准备试一下单张图片识别情况，我发现Android端是根据捕获视频流每帧数据识别的，我将图片转为bitmap格式传入后无法识别，后又将bitmap转为yue格式，还是无法识别，求解惑

**Comment by lsy17096535** [comment]
yuv的nv21格式

**Comment by Siwroae** [comment]
/*
     * 获取位图的YUV数据
     */
    public static byte[] getYUVByBitmap(Bitmap bitmap) {
        if (bitmap == null) {
            return null;
        }
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        if ((width & 1) == 1) {
            width = width -1;
        }
        if ((height & 1) == 1) {
            height = height -1;
        }
        int size = width * height;

        int pixels[] = new int[size];
        bitmap.getPixels(pixels, 0, width, 0, 0, width, height);

        // byte[] data = convertColorToByte(pixels);
        byte[] data = rgb2YCbCr420(pixels, width, height);

        return data;
    }

 public static byte[] rgb2YCbCr420(int[] pixels, int width, int height) {
        int len = width * height;
        // yuv格式数组大小，y亮度占len长度，u,v各占len/4长度。
        byte[] yuv = new byte[len * 3 / 2];
        int y, u, v;
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                // 屏蔽ARGB的透明度值
                int rgb = pixels[i * width + j] & 0x00FFFFFF;
                // 像素的颜色顺序为bgr，移位运算。
                int r = rgb & 0xFF;
                int g = (rgb >> 8) & 0xFF;
                int b = (rgb >> 16) & 0xFF;
                // 套用公式
                y = ((66 * r + 129 * g + 25 * b + 128) >> 8) + 16;
                u = ((-38 * r - 74 * g + 112 * b + 128) >> 8) + 128;
                v = ((112 * r - 94 * g - 18 * b + 128) >> 8) + 128;
                // rgb2yuv
                // 调整
                y = y < 16 ? 16 : (y > 255 ? 255 : y);
                u = u < 0 ? 0 : (u > 255 ? 255 : u);
                v = v < 0 ? 0 : (v > 255 ? 255 : v);
                // 赋值
                yuv[i * width + j] = (byte) y;
                yuv[len + (i >> 1) * width + (j & ~1) + 0] = (byte) u;
                yuv[len + +(i >> 1) * width + (j & ~1) + 1] = (byte) v;
            }
        }
        return yuv;
    }

**Comment by Siwroae** [comment]
> YUV的NV21格式

我已经将自己转yuv格式的代码贴在下面了，求看一下有什么问题么

**Comment by Siwroae** [comment]
> YUV的NV21格式
图片转nv21格式前需要对图片做其他操做么，比如旋转之类的

**Comment by Siwroae** [comment]
> 昨天准备试一下单张图片识别情况，我发现Android端是根据捕获视频流每帧数据识别的，我将图片转为bitmap格式传入后无法识别，后又将bitmap转为yue格式，还是无法识别，求解惑
