### ISSUE TITLE
Android arm64-v8a so无法使用

### ISSUE THREAD

**Issue by JianbangZ** [zeusees/HyperLandmark#51]
当没有人脸的时候可以运行，当出现人脸就会出现崩溃问题
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4142 (DrawFacePointsT), pid 4055 (m.hyperlandmark)

**Comment by androidGhost** [comment]
有可能是编译出错了，看提交记录是arm64-v8不是arm64-v8a,这个需要作者查看一下

**Comment by JianbangZ** [comment]
@szad670401 麻烦可以看一下arm64-v8a so无法使用的问题吗？

**Comment by androidGhost** [comment]
麻烦作者有时间抽空看看，arm64-v8a so文件不能使用，谢谢

**Comment by JianbangZ** [comment]
@lsy17096535 updates?

**Comment by nhancv** [comment]
I really need the arm64-v8a fixed version also, the play store requires it now. Please.

**Comment by androidGhost** [comment]
谷歌市场要求8月前添加64位支持，时间还早，你用谷歌开源的人脸识别也可以啊

**Comment by nhancv** [comment]
> The Google market requires 64-bit support before August. It’s still early, you can use Google’s open source face recognition.

I had tried Google's libraries, I prefer HyperLandmark with high efficiency (speed and more landmarks)

**Comment by fire717** [comment]
同问，这个问题现在还没解决吗？

**Comment by netdrop-sys** [comment]
已经解决
