### ISSUE TITLE
Android底层C代码有开源计划吗

### ISSUE THREAD

**Issue by xiaozhi003** [zeusees/HyperLandmark#56]
首先感谢作者开源了如此好的东西
如题，so库是否开源计划呢，现在只限于使用，没法做进一步研究了

**Comment by lsy17096535** [comment]
@xiaozhi003 实在不好意思，我们暂时不能开源底层so的代码，但是我们后期会考虑把这部分代码放出来，也会及时更新git。如果使用中有什么问题，及时提出，我们尽快解决。

**Comment by xiaozhi003** [comment]
哈哈，是无限期延后吗

**Comment by xiaozhi003** [comment]
@lsy17096535 哈哈，是无限期延后吗
