### ISSUE TITLE
对landmark的跟踪比较感兴趣， 请问下track的部分有没开源的计划？ 或者目前跟踪用的是什么算法？ 有没相关论文？谢谢

### ISSUE THREAD

**Issue by zouxinhua** [zeusees/HyperLandmark#58]

**Comment by lsy17096535** [comment]
如果是单纯的物体跟踪，可以参考一些最近两年的优秀跟踪算法，一般快速跟踪KCF等，也可以。人脸跟踪可以用模板匹配等简单的跟踪，这样处理速度快。

**Comment by zouxinhua** [comment]
@lsy17096535  感谢回复， 是这样的，我自己有个landmark detect的算法， 但是达不到实时的要求， 所以视频场景用不起来， 但是我看HyperLandmark的demo apk是能达到实时的性能要求， 我想知道的是用的landmark点跟踪的算法还是说landmark detect性能很好， 每一帧都进行landmark detect ？

**Comment by lsy17096535** [comment]
landmark detect性能好一些
