### ISSUE TITLE
APK安装失败

### ISSUE THREAD

**Issue by coldcoda** [zeusees/HyperLandmark#59]
您好,apk的安装对android版本有要求吗?为什么总是安装失败呢?

**Comment by lsy17096535** [comment]
@coldcoda  你好，麻烦您提供一下Android的手机型号跟系统版本，我们复现解决。

**Comment by coldcoda** [comment]
android 5.1 , vivoX6d

**Comment by lsy17096535** [comment]
我们没有找到vivox6d,找了另外一个vivo 5.1 的手机可以了，你测试一下我们提供的demo，没问题的话我们更新一下Android sdk。

**Comment by coldcoda** [comment]
你好,请问提供的demo怎么获得呢?还是之前的apk链接吗?

**Comment by lsy17096535** [comment]
对

**Comment by coldcoda** [comment]
https://fir.im/HyperLandmark链接下载的安装包,还是一直安装失败
