### ISSUE TITLE
检测眼睛闭合度问题

### ISSUE THREAD

**Issue by JunGenius** [zeusees/HyperLandmark#60]
你好，作者。
首先非常感谢你们开源，然后我想请教几个问题:
     在 windows 下 ， 我想通过眼睛的睁开角度和上下眼皮睁开的距离来判断正闭眼，现在测试发现当人脸倾斜角度稍微大的时候，经常识别不出来。以及当闭眼时候，眼睛特征点识别的也不是太理想，经常识别到眼皮上了 ，请问下，有什么好的解决办法吗 ？ 或者有什么优化的思路吗 ？

  非常感谢，期待你们的解决。

**Comment by lsy17096535** [comment]
一个可以通过丰富的训练数据解决，另外网络的设计也要继续优化。
