### ISSUE TITLE
how to train landmark?

### ISSUE THREAD

**Issue by wangpupanjing** [zeusees/HyperLandmark#65]
hi 
可以讲一下怎么训练的landmark吗？采用什么算法和什么数据？

**Comment by lsy17096535** [comment]
可以参考这个repo：https://github.com/guoqiangqi/PFLD

**Comment by xuguozhi** [comment]
发现作者在官网挂的PFLD-Demo里，PFLD/app/src/main/java 有用你们的模型：
tree .
.
├── AndroidManifest.xml
├── assets
│   └── FaceTracking
│       └── models
│           ├── det1.bin
│           ├── det1.param
│           ├── det2.bin
│           ├── det2.param
│           ├── det3.bin
│           ├── det3.param
│           ├── tracking.bin
│           └── tracking.proto.bin
├── java
│   ├── com
│   │   └── sample
│   │       └── tracking
│   │           ├── CameraOverlapFragment.java
│   │           ├── FaceOverlapFragment.java
│   │           ├── FaceTrackerActivity.java
│   │           └── FixedAspectRatioFrameLayout.java
│   └── zeusees
│       └── tracking
│           ├── Face.java
│           └── FaceTracking.java

你们的算法之间有什么关联吗？

**Comment by lsy17096535** [comment]
合作开发的

**Comment by xuguozhi** [comment]
Great! 有计划迁移到嵌入式板子上面么？比如RK3399 pro、TVM/MNN这些框架

**Comment by lsy17096535** [comment]
后期会移植多个平台。
