### ISSUE TITLE
Android版，提取Landmark的模型是什么？

### ISSUE THREAD

**Issue by rexhz** [zeusees/HyperLandmark#66]
我看封装在tracking模块里面了，106点提取的模型是什么？用了几个github上其他的模型，发现不稳定，但是你这个demo好像还是比较稳定。

**Comment by lsy17096535** [comment]
我们把跟踪和landmark都放在了底层，这部分没有开始，实在对不住。稳定化有很多方法，可以做两帧的平滑，或者其他滤波。

**Comment by KangolHsu** [comment]
可以这么理解吗？
1.你们的特征点检测Android模型就是tracking.bin 和tracking.proto.bin
2.你们的landmark检测和跟踪算法应该是封装在libzeuseesTracking-lib.so
对不？
