### ISSUE TITLE
landmark精确度和其他方法(lbfmodel/dlib)的比较？

### ISSUE THREAD

**Issue by peacherwu** [zeusees/HyperLandmark#69]
有木有人做过和lbfmodel和dlib脸部特征点的准确度比较:

- [https://github.com/kurnianggoro/GSOC2017/blob/master/data/lbfmodel.yaml](https://github.com/kurnianggoro/GSOC2017/blob/master/data/lbfmodel.yaml)

- [https://github.com/davisking/dlib-models/blob/master/shape_predictor_68_face_landmarks.dat.bz2](https://github.com/davisking/dlib-models/blob/master/shape_predictor_68_face_landmarks.dat.bz2)

**Comment by lsy17096535** [comment]
我们是基于106点进行的关键点计算，目前没有开放的106测评数据集，主观体验的提交更为直观。
