### ISSUE TITLE
What kind of method to achieve landmark stabilization?

### ISSUE THREAD

**Issue by John1231983** [zeusees/HyperLandmark#72]
Thanks for sharing it. I run your code with pfld ported from tensorflow code and the landmark results in unstable although the face is not moving. Could you suggest the solution/method to fix it? your method provides the landmark stabilization.

**Comment by lsy17096535** [comment]
you can reference SDM algorithm (https://github.com/chengzhengxin/sdm).

**Comment by John1231983** [comment]
@lsy17096535 : So given a landmark points (106) predicted from PFLD model, you will feed it to SDM model to obtain a stable landmark. Is it right? The pipeline will be
```
input image --> PFLD --> 106 points --> SDM-->106 points
```
