### ISSUE TITLE
How to achieve realtime inference?

### ISSUE THREAD

**Issue by John1231983** [zeusees/HyperLandmark#75]
Hi, the inference code runs very fast. Could you tell me any trick to obtain the realtime inference? Does it run on GPU or CPU?

**Comment by lsy17096535** [comment]
Android app running on arm cpu with ncnn. if you want design a realtime landmark detector, a lightweight network is needed.

**Comment by John1231983** [comment]
>lightweight network
I am using mobilenet v2 with alpha 0.25 as the paper mention. Do you use same thing or customize the mobilenet v2? Any suggestion?

**Comment by lsy17096535** [comment]
mobilenet v2 is ok

**Comment by John1231983** [comment]
Thanks. But I found that the speed is still slow. I used canvas to draw the landmark points. Is it fine?

**Comment by lsy17096535** [comment]
If you running on android or ios devices, draw points based on opengl.

**Comment by John1231983** [comment]
opengl is faster than canvas API function. Is it right? Thanks so much

**Comment by lsy17096535** [comment]
yes
