### ISSUE TITLE
预览摄像分辨率越高，检测人脸延时越高

### ISSUE THREAD

**Issue by AndroidLi123** [zeusees/HyperLandmark#78]
预览摄像分辨率越高，检测人脸延时越高。有个大概的数据范围给出吗？比如在什么分辨率下，检测延时的对比度

**Comment by lsy17096535** [comment]
我们一般采用640*480，这个在主流机器上大概7ms，另外960*540的分辨率也用，主流机器要接近20ms。

**Comment by AndroidLi123** [comment]
明白了谢谢
