### ISSUE TITLE
Could you cancel the Log Warn/Info

### ISSUE THREAD

**Issue by BigFishMaster** [zeusees/HyperLandmark#87]
I run this app and find this following log:
```bash
W/DrawFacePointsT: type=1400 audit(0.0:6909503): avc: granted { write } for pid=31087 name="demo2.jpg" dev="sdcardfs" ino=23785 scontext=u:r:untrusted_app_27:s0:c62,c257,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
W/DrawFacePointsT: type=1400 audit(0.0:6909504): avc: granted { write open } for pid=31087 path="/storage/emulated/0/demo2.jpg" dev="sdcardfs" ino=23785 scontext=u:r:untrusted_app_27:s0:c62,c257,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
```
My questions:
1. Is this log from so files?
2. What does it mean?
3. How to cancel it?

**Comment by netdrop-sys** [comment]
ok, we will set a parameter control this Log info.

**Comment by BigFishMaster** [comment]
@netdrop-sys It is not only the log, but also a screenshot image named "demo2.jpg" will be saved the storage. Please check this, I think it is not neccessary to do screenshot.

**Comment by BigFishMaster** [comment]
I find the new PR. I will try it and then close this issue if it is resolved.
