### ISSUE TITLE
眸子处两个关键点

### ISSUE THREAD

**Issue by huangdade** [zeusees/HyperLandmark#91]
注意到眸子处有两个关键点。这两个点有什么区别吗？
![图片](https://user-images.githubusercontent.com/4537048/82436632-b63fe980-9ac8-11ea-90e2-3dfaeabb1cf6.png)

**Comment by netdrop-sys** [comment]
是两个点，其中一个点代表眼睛的中心点，另外一个是眼球的点。

**Comment by huangdade** [comment]
原来如此。那分别是怎么对应的？哪一个点是眼球的点呢？

**Comment by netdrop-sys** [comment]
好像是36和70，你可以自己显示一下。
