### ISSUE TITLE
高概率 crash

### ISSUE THREAD

**Issue by LiaoSu** [zeusees/HyperLandmark#96]
06-20 18:05:01.322  5906  5906 F DEBUG   : backtrace:
06-20 18:05:01.322  5906  5906 F DEBUG   :     #00 pc 000000000002216c  /system/lib64/libc.so (abort+116)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #01 pc 00000000004dad1c  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (__kmp_abort_process+44)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #02 pc 00000000004d4190  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (__kmp_msg+512)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #03 pc 0000000000509170  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so
06-20 18:05:01.322  5906  5906 F DEBUG   :     #04 pc 00000000004dbf5c  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (__kmp_allocate_team+2216)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #05 pc 00000000004dcb0c  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (__kmp_fork_call+2384)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #06 pc 00000000004c4ec8  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (__kmpc_fork_call+156)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #07 pc 000000000017d788  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so
06-20 18:05:01.322  5906  5906 F DEBUG   :     #08 pc 00000000000a4714  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so
06-20 18:05:01.322  5906  5906 F DEBUG   :     #09 pc 0000000000098a70  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (MTCNN::PNet()+564)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #10 pc 0000000000099d6c  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (MTCNN::detect(ncnn::Mat&, std::vector<Bbox, std::allocator, <Bbox>>&)+292)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #11 pc 000000000009e940  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (FaceTracking::detecting(cv::Mat*)+108)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #12 pc 000000000009d9cc  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (FaceTracking::update(cv::Mat&)+952)
06-20 18:05:01.322  5906  5906 F DEBUG   :     #13 pc 000000000009d0e8  /data/app/com.-b-6dMmPXBqKslKMnVQYiZg==/lib/arm64/libzeuseesTracking-lib.so (Java_com_zeusee_main_hyperlandmark_jni_FaceTracking_update+640)

**Comment by netdrop-sys** [comment]
感谢提出问题，看样子是人脸初定位的时候除了问题，我们查看一下。

**Comment by yangkezun** [comment]
把build目录删除，重新编译。

**Comment by jaikishan01** [comment]
i want a good beauty camera app source code i am willing to pay please r8 on at pande.jaikishan@gmail.com

**Comment by Roben1016** [comment]
你好，问题还是会出现，请问有解决办法吗

**Comment by CLIsVeryOK** [comment]
您的来信已收到，谢谢！陈雷同济大学测绘与地理信息学院Thanks for your attention.Chen Lei
College of survey and geo-information of Tongji university
